name: Update Nodes

on:
  push:
    branches:
      - main
    paths:
      - 'nodes.json'
permissions:
  contents: write

jobs:
  remove_duplicates:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Corepack
        run: |
          corepack disable
          rm -rf ~/.cache/corepack
          npm install -g corepack
          corepack enable
          corepack prepare pnpm@latest --activate || (corepack enable && corepack prepare pnpm@latest --activate)

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: "pnpm"

      - name: Install Dependencies
        working-directory: apps/workflows
        run: pnpm install || (rm -rf node_modules && pnpm install)

      - name: Build
        working-directory: apps/workflows
        run: pnpm build

      - name: Run TypeScript Script
        working-directory: apps/workflows
        env:
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
        run: pnpm start

      - name: Commit Changes to nodes.json
        working-directory: apps/workflows
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update Nodes"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git main
        
